### ISSUE TITLE
Resources Lab

### ISSUE THREAD

**Issue by paulcompton** [paulcompton/SEBC#4]

**Comment by paulcompton** [comment]
I have the following warning that I have worked around by providing the name node details
Warning: fs.defaultFS is not set when running "rm" command.
Deleted hdfs://ip-172-31-5-110.ap-southeast-2.compute.internal/results/tg-10GB-16-16-1024

**Comment by mfernest** [comment]
The error above likely meant you did not have HDFS Gateway roles installed on the host. The Gateway is a collection of client configuration files that CM monitors.

**Comment by mfernest** [comment]
Nice work. Wrong chart page on the last exercise, or you took the snap before you ran your tests.
